using System.Text;

namespace CtrlAgent.Core;

public enum ValidationOutcome
{
    NotTested = 0,
    Pass,
    Fail,
    Skipped,
}

public sealed record ValidationCheck(
    string Id,
    string Title,
    ValidationOutcome Outcome,
    string? Notes = null);

/// <summary>
/// Result of one hardware validation run, rendered to the markdown evidence
/// format required by docs/controller-validation.md. The go/no-go gates match
/// that document: standard controls, reconnect, and at least two distinct
/// rumble cues are hard gates; paddles degrade to "experimental" instead of
/// blocking.
/// </summary>
public sealed record ValidationReport(
    string DeviceName,
    string AdapterId,
    string Transport,
    string OperatingSystem,
    string Framework,
    ControllerCapabilities Capabilities,
    IReadOnlyList<ValidationCheck> Checks,
    string PaddleObservations,
    string RumbleObservations,
    string Anomalies,
    DateTimeOffset GeneratedAt)
{
    public const string StandardControlsCheckId = "standard-controls";
    public const string ReconnectCheckId = "reconnect";
    public const string RumbleCheckId = "rumble";
    public const string PaddlesCheckId = "paddles";

    public bool IsGo =>
        OutcomeOf(StandardControlsCheckId) == ValidationOutcome.Pass &&
        OutcomeOf(ReconnectCheckId) == ValidationOutcome.Pass &&
        OutcomeOf(RumbleCheckId) == ValidationOutcome.Pass;

    public bool PaddlesIndependent => OutcomeOf(PaddlesCheckId) == ValidationOutcome.Pass;

    public string Recommendation
    {
        get
        {
            if (!IsGo)
            {
                var failing = new List<string>();
                AddIfNotPass(failing, StandardControlsCheckId, "standard controls");
                AddIfNotPass(failing, ReconnectCheckId, "reconnect");
                AddIfNotPass(failing, RumbleCheckId, "rumble");
                return $"NO-GO: resolve {string.Join(", ", failing)} before relying on this transport.";
            }

            return PaddlesIndependent
                ? "GO: all gates passed; paddles are independently usable on this transport."
                : "GO with caveat: core gates passed, but paddles are not independently verified — treat paddle bindings as experimental and rely on the XInput fallback chords.";
        }
    }

    public static string SuggestFileName(DateTimeOffset date, string transport) =>
        $"{date:yyyy-MM-dd}-elite-series-2-{Sanitize(transport)}.md";

    public string ToMarkdown()
    {
        var builder = new StringBuilder();

        builder.AppendLine($"# Elite Series 2 validation — {Transport}");
        builder.AppendLine();
        builder.AppendLine($"Generated by CtrlAgent `--validate` on {GeneratedAt:yyyy-MM-dd HH:mm zzz}.");
        builder.AppendLine();

        builder.AppendLine("## Environment");
        builder.AppendLine();
        builder.AppendLine($"- Device: {DeviceName}");
        builder.AppendLine($"- Adapter: {AdapterId}");
        builder.AppendLine($"- Transport: {Transport}");
        builder.AppendLine($"- Operating system: {OperatingSystem}");
        builder.AppendLine($"- Runtime: {Framework}");
        builder.AppendLine(
            $"- Capabilities: paddles={Format(Capabilities.HasFourPaddles)}, " +
            $"low={Format(Capabilities.HasLowFrequencyRumble)}, high={Format(Capabilities.HasHighFrequencyRumble)}, " +
            $"leftTrigger={Format(Capabilities.HasLeftTriggerRumble)}, rightTrigger={Format(Capabilities.HasRightTriggerRumble)}");
        builder.AppendLine();

        builder.AppendLine("## Pass/fail");
        builder.AppendLine();
        builder.AppendLine("| Test | Result | Notes |");
        builder.AppendLine("|---|---|---|");
        foreach (var check in Checks)
        {
            builder.AppendLine($"| {check.Title} | {check.Outcome} | {check.Notes ?? string.Empty} |");
        }

        builder.AppendLine();

        builder.AppendLine("## Paddle observations");
        builder.AppendLine();
        builder.AppendLine(string.IsNullOrWhiteSpace(PaddleObservations) ? "None recorded." : PaddleObservations);
        builder.AppendLine();

        builder.AppendLine("## Rumble observations");
        builder.AppendLine();
        builder.AppendLine(string.IsNullOrWhiteSpace(RumbleObservations) ? "None recorded." : RumbleObservations);
        builder.AppendLine();

        builder.AppendLine("## Known anomalies");
        builder.AppendLine();
        builder.AppendLine(string.IsNullOrWhiteSpace(Anomalies) ? "None reported." : Anomalies);
        builder.AppendLine();

        builder.AppendLine("## Recommendation");
        builder.AppendLine();
        builder.AppendLine(Recommendation);

        return builder.ToString();
    }

    private ValidationOutcome OutcomeOf(string id) =>
        Checks.FirstOrDefault(check => check.Id == id)?.Outcome ?? ValidationOutcome.NotTested;

    private void AddIfNotPass(List<string> failing, string id, string label)
    {
        if (OutcomeOf(id) != ValidationOutcome.Pass)
        {
            failing.Add($"{label} ({OutcomeOf(id)})");
        }
    }

    private static string Format(bool value) => value ? "yes" : "no";

    private static string Sanitize(string transport)
    {
        var builder = new StringBuilder(transport.Length);
        foreach (var character in transport.ToLowerInvariant())
        {
            builder.Append(char.IsAsciiLetterOrDigit(character) ? character : '-');
        }

        return builder.ToString().Trim('-');
    }
}
